FullKeyboard=no
JoyButton-0=0,Ignore
JoyButton-1=1,A
JoyButton-2=2,B
JoyButton-3=3,Y
JoyButton-4=4,X
JoyButton-5=5,L
JoyButton-6=6,R
JoyButton-7=7,Select
JoyButton-8=8,Start
JoyButton-9=9,Menu
JoyButton-10=10,StickClick
JoyButton-11=11,HelpI
JoyButton-12=12,Up
JoyButton-13=13,Down
JoyButton-14=14,Left
JoyButton-15=15,Right
JoyAxis-0=-1,Left
JoyAxis-1=1,Right
JoyAxis-2=-2,Up
JoyAxis-3=2,Down
