#
# uMTP Responder config file
#

loop_on_disconnect 1
wait 1

storage "/userdata" "Userdata"

manufacturer "Batocera"
product "Batocera Device"
serial "00000001"
interface "MTP"

usb_vendor_id  0x1D6B
usb_product_id 0x0100
usb_class 0x6
usb_subclass 0x1
usb_protocol 0x1

usb_dev_version 0x3008

usb_functionfs_mode 0x1

usb_dev_path   "/dev/ffs-umtp/ep0"
usb_epin_path  "/dev/ffs-umtp/ep1"
usb_epout_path "/dev/ffs-umtp/ep2"
usb_epint_path "/dev/ffs-umtp/ep3"

usb_max_packet_size 0x200
