################################################################################
#
# xenia-canary
#
################################################################################

XENIA_CANARY_VERSION = 9478cda5d643f31ce5eddaa3a698282887515439
XENIA_CANARY_SITE = https://github.com/xenia-canary/xenia-canary.git
XENIA_CANARY_SITE_METHOD = git
XENIA_CANARY_GIT_SUBMODULES = YES
XENIA_CANARY_LICENSE = BSD
XENIA_CANARY_LICENSE_FILE = LICENSE
XENIA_CANARY_SUPPORTS_IN_SOURCE_BUILD = NO

XENIA_CANARY_WINDOWS_VERSION = 505697f
XENIA_CANARY_WINDOWS_SOURCE = xenia_canary_windows.zip
XENIA_CANARY_EXTRA_DOWNLOADS = \
	https://github.com/xenia-canary/xenia-canary/releases/download/$(XENIA_CANARY_WINDOWS_VERSION)/$(XENIA_CANARY_WINDOWS_SOURCE)

XENIA_CANARY_DEPENDENCIES = host-pkgconf alsa-lib fontconfig libgtk3 lz4 python-toml \
	sdl2 vulkan-headers vulkan-loader xlib_libX11 libxcb

XENIA_CANARY_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
XENIA_CANARY_CONF_OPTS += -DXENIA_BUILD_TESTS=OFF
XENIA_CANARY_CONF_OPTS += -DXENIA_BUILD_MISC=OFF
XENIA_CANARY_CONF_OPTS += -DXENIA_ENABLE_LTO=OFF

define XENIA_CANARY_GEN_VERSION_H
	mkdir -p $(@D)
	printf '// Autogenerated by batocera buildroot.\n\
#ifndef GENERATED_VERSION_H_\n\
#define GENERATED_VERSION_H_\n\
#define XE_BUILD_BRANCH "canary"\n\
#define XE_BUILD_COMMIT "$(XENIA_CANARY_VERSION)"\n\
#define XE_BUILD_COMMIT_SHORT "$(shell echo $(XENIA_CANARY_VERSION) | cut -c1-9)"\n\
#define XE_BUILD_DATE __DATE__\n\
#define XE_BUILD_PR_NUMBER 0\n\
#endif  // GENERATED_VERSION_H_\n' > $(@D)/version.h
endef

XENIA_CANARY_PRE_CONFIGURE_HOOKS += XENIA_CANARY_GEN_VERSION_H

define XENIA_CANARY_INSTALL_TARGET_CMDS
	mkdir -p $(TARGET_DIR)/usr/xenia-canary
	rm -rf $(@D)/windows-package
	mkdir -p $(@D)/windows-package
	$(UNZIP) -q -o -d $(@D)/windows-package \
		$(DL_DIR)/$(XENIA_CANARY_DL_SUBDIR)/$(XENIA_CANARY_WINDOWS_SOURCE)
	rsync -a --exclude=".*" $(@D)/windows-package/ $(TARGET_DIR)/usr/xenia-canary/
	find $(@D) -maxdepth 6 -name "xenia_canary" -type f -perm /111 \
	    | head -1 \
	    | xargs -I{} $(INSTALL) -D -m 0755 {} $(TARGET_DIR)/usr/xenia-canary/xenia_canary
	mkdir -p $(TARGET_DIR)/usr/bin
	ln -sf /usr/xenia-canary/xenia_canary $(TARGET_DIR)/usr/bin/xenia-canary
endef

define XENIA_CANARY_POST_PROCESS
	mkdir -p $(TARGET_DIR)/usr/xenia-canary/patches
	mkdir -p $(TARGET_DIR)/usr/share/xenia-canary/patches
	mkdir -p $(@D)/temp
	( cd $(@D)/temp && $(GIT) init && \
	  $(GIT) remote add origin https://github.com/xenia-canary/game-patches.git && \
	  $(GIT) config core.sparsecheckout true && \
	  echo "patches/*.toml" >> .git/info/sparse-checkout && \
	  $(GIT) pull --depth=1 origin main && \
	  cp -f patches/*.toml $(TARGET_DIR)/usr/share/xenia-canary/patches && \
	  cp -f patches/*.toml $(TARGET_DIR)/usr/xenia-canary/patches \
	)
	rm -rf $(@D)/temp
endef

XENIA_CANARY_POST_INSTALL_TARGET_HOOKS = XENIA_CANARY_POST_PROCESS

$(eval $(cmake-package))
